vars = Variables(None, ARGUMENTS)

vars.Add(BoolVariable('debug_symbols',
    help='decides if debug symbols are needed',
    default="false",
  )
)

vars.Add(EnumVariable('opt',
    help='Decides level of optimisation (0, 1, 2, 3)',
    default="3",
    allowed_values=('0', '1', '2', '3'),
  )
)

env = Environment(variables=vars)

flag_array = ["-I.", "-Wall", "-std=c++17"]

debug_symbols = env["debug_symbols"]
opt_level = env["opt"]
if debug_symbols:
  flag_array.append("-g")
flag_array.append("-O{0}".format(opt_level))


ccflags = " ".join(flag_array)
env["CPPFLAGS"] = ccflags

env.SConscript(["core/SConscript", "main/SConscript", "api/SConscript"], 'env')

env.Program("bin/prog", ["main/main", "core/core", "api/api"])
