FROM python:slim-buster
# Creates the actual service

# Copy the needed files
COPY SingleSuit/ /SingleSuit/

RUN mkdir /Worker

COPY Worker/ /Worker/

WORKDIR /Worker

# Install dependencies
RUN pip3 install pika

# Set environment
ENV EXEC_PATH=/SingleSuit/run.sh
ENV GAME_NAME=singlesuit

RUN chmod +x $EXEC_PATH

CMD ["bash", "./run_fullservice.sh"]

