FROM python:slim-buster

RUN apt update && apt install -y build-essential

# Copy the needed files
COPY Whistette/ /Whistette/

RUN cd Whistette && make


FROM python:slim-buster
# Creates the actual service

COPY --from=0 /Whistette/a.out /bin/whistette

RUN mkdir /Worker

COPY Worker/ /Worker/

WORKDIR /Worker

# Install dependencies
RUN pip3 install pika

# Set environment
ENV EXEC_PATH=/bin/whistette
ENV GAME_NAME=whistette

RUN chmod +x $EXEC_PATH

CMD ["bash", "./run_fullservice.sh"]

