FROM python:slim-buster
# Creates the actual service

# Copy the needed files
COPY SingleSuit/ /SingleSuit/

RUN mkdir /Worker

COPY Worker/ /Worker/

WORKDIR /Worker

# Install dependencies
RUN pip3 install pika

# Set environment
ENV EXEC_PATH=/SingleSuit/main.py
ENV GAME_NAME=singlesuit
ENV PYTHONPATH=/SingleSuit/solver

RUN chmod +x $EXEC_PATH

CMD ["python3", "main.py"]

