// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GameCreateRequest struct {
	GameName   string `json:"game_name"`
	StartState string `json:"start_state"`
}

type GameInfo struct {
	ID          string `json:"id"`
	PlayerCount int    `json:"player_count"`
	GameName    string `json:"game_name"`
	EventClock  int    `json:"event_clock"`
	State       string `json:"state"`
}
