// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GameInfo struct {
	ID            string   `json:"id"`
	PlayersJoined []string `json:"players_joined"`
	GameName      string   `json:"game_name"`
	EventClock    int      `json:"event_clock"`
	State         string   `json:"state"`
	IsReady       bool     `json:"is_ready"`
	IsFinished    bool     `json:"is_finished"`
	Winner        string   `json:"winner"`
}
